[package]
name = "simple-boot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nrf9160-pac = "0.11.0"
cortex-m = "0.7"
cortex-m-rt = "0.7"
nrf9160-boot = { path = "../" }